//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Active
    {
        public string PERSONID { get; set; }
        public string PERSONNAME { get; set; }
        public int ITEMID { get; set; }
        public System.DateTime DATE { get; set; }
        public string TRANSACTIONID { get; set; }
        public int EFID { get; set; }
    }
}
