//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public string TRANSACTIONID { get; set; }
        public string PERSONID { get; set; }
        public string PERSONNAME { get; set; }
        public int ITEMID { get; set; }
        public string TRANSACTIONDATE { get; set; }
        public Nullable<int> TRANSACTIONTYPE { get; set; }
        public int EFID { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
